### ISSUE TITLE
Commit 6a414d4fef6aa1dc75e768929a14f066053e0556 ("src/ws63flash.c: Support baudrate negotiation during handshake & Make it default") 测试请求

### ISSUE THREAD

**Issue by goodspeed34** [MiraHikari/nearlink-firmwares#3]
这个 commit 应该能实现让 ws63flash  切换 Hi2821, Hi3861 的烧录波特率。使用方法和之前一致，如果需要之前的烧录波特率协商方式可以使用 `--late-baud` 选项。

我没有 Hi2821, Hi3861 等设备，但已经验证此方法在 WS63 上可以工作。希望能帮忙测试一下。

CI 的二进制构建：https://github.com/goodspeed34/ws63flash/actions/runs/11875809694/artifacts/2197622004

**Comment by Hny0305Lin** [comment]
收到，感谢项目原作者来提交issue，我们会在最近与项目成员共同参与测试，@MiraHikari @Burial0268

**Comment by Burial0268** [comment]
再次感谢开发者能够提交issue，我们现在正在测试中

**Comment by goodspeed34** [comment]
The commit was tested and released. https://github.com/goodspeed34/ws63flash/releases/tag/v0.2.2

**Comment by Hny0305Lin** [comment]
我们团队最近测试也是成功的，并且还将为您们0.2.2 Release版，做更多烧写场景与功能展示。具体我们公开的视频demo展示🔗[点我访问](https://b23.tv/zYLUGe4)

**Comment by goodspeed34** [comment]
Thanks for the followup. Happy holidays. :)
